// components/features/memberzone/MemberzoneSection.vue
<script setup lang="ts">
import mock from '@/data/mock.json'
const { data, sidebar, templateFor } = defineProps<{
  data: any
  sidebar?: string
  templateFor: string
  isSidebar?: boolean
  ssoUrl: string
}>()

const userSubscription = [
  {
    name: 'Tempo Plus',
    logo: '/img/t_plus_logo.svg',
    link: 'https://tempo.co/',
    status: 'Aktif',
  },
  {
    name: 'Tempo VIP',
    logo: '/img/t_vip_logo.svg',
    link: 'https://membership.tempo.co/',
    status: 'Tidak Aktif',
  },
  {
    name: 'Teras',
    logo: '/img/teras_initial_logo.svg',
    link: 'https://teras.id/',
    status: 'Aktif',
  }
]

let orderedSubscriptions = [...userSubscription] // clone to avoid mutation

if (templateFor.toLowerCase() === 'teras') {
  // Move 'Teras' to the front
  const terasIndex = orderedSubscriptions.findIndex(
    (subscription) => subscription.name === 'Teras'
  )
  if (terasIndex > -1) {
    const [terasItem] = orderedSubscriptions.splice(terasIndex, 1)
    orderedSubscriptions.unshift(terasItem)
  }
} else if (templateFor.toLowerCase() === 'tempo') {
  // Move 'Tempo Plus' to the front, then 'Teras', then 'Tempo VIP'
  orderedSubscriptions.sort((a, b) => {
    const order = ['Tempo Plus', 'Teras', 'Tempo VIP']
    return order.indexOf(a.name) - order.indexOf(b.name)
  })
}

function getSubscriptionStatus(name: string) {
  // Map subscription names to content_access keys
  console.log('data', data)
  const accessMap: Record<string, string> = {
    'Tempo Plus': 'tempo_plus',
    'Teras': 'teras_plus',
    'Tempo VIP': 'tempo_vip',
  }
  const key = accessMap[name]
  if (!key) return 'Tidak Aktif'
  return data.content_access && data.content_access.includes(key) ? 'Aktif' : 'Tidak Aktif'
}

</script>

<template>
  <client-only>
    <div :class="sidebar && 'w-full max-h-[90dvh] pb-20 lg:pb-0 overflow-y-auto'">
      <div class="overflow-hidden flex gap-3 px-6 py-4">
        <div>
          <figure class="bg-white h-[61px] w-[61px] relative overflow-hidden rounded-full">
            <p class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 font-semibold text-xl text-[#D61D23]">
              {{ data.initial.toUpperCase() }}
            </p>
          </figure>
        </div>
        <div>
          <p class="text-lg font-semibold text-neutral-1100 leading-6 line-clamp-1 mb-1">
            {{ data.fullname }}
          </p>
          <p class="text-sm font-semibold text-[#757575] leading-4 line-clamp-1 mb-1 lg:min-w-52">
            {{ data.email }}
          </p>
          <p class="text-sm font-normal text-[#757575] leading-4">
            Tempo ID : {{ data.id }}
          </p>
        </div>
      </div>
      <div v-if="!isSidebar" class="px-5">
        <p class="text-lg font-bold mb-4">
            Status Langganan
        </p>
        <div class="container bg-white rounded-xl p-5">
          <div v-for="(subscription, index) in orderedSubscriptions" :key="index + subscription.name" class="flex gap-3 items-center pb-4 mb-4 border-b border-[#EEEEEE]">
            <nuxt-img
              :src="subscription.logo"
              :alt="`Logo ${subscription.name} Initial`"
              class="mt-1"
              width="19px"
              height="19px"
            />
            <nuxt-link :to="subscription.link" class="text-sm underline font-semibold text-neutral-1200" external>
              {{ subscription.name }}
            </nuxt-link>
            <p
              class="text-xs font-semibold ms-auto py-1 px-2"
              :class="getSubscriptionStatus(subscription.name) === 'Aktif' ? 'bg-[#F6FFF8] text-[#43A047]' : 'bg-[#FFF3F2] text-[#FD1515]'"
            >
              {{ getSubscriptionStatus(subscription.name) }}
            </p>
          </div>

          <ui-button-primary class="w-full mt-4">
            <nuxt-link class="block w-full h-full" to="https://tempo.co/users/subscriptions" target="_blank">
              Lihat Detail Langganan
            </nuxt-link>
          </ui-button-primary>
        </div>
      </div>
    <memberzone-menus :template-for="templateFor" :is-sidebar="isSidebar" :sso-url="ssoUrl" />
    <div v-if="templateFor === 'teras'" class="px-5 mt-4">
      <social-media-teras :social-media="mock.socialMediaTeras" />
    </div>
    </div>
  </client-only>
</template>

// src/components/Memberzone/MemberzoneSection.tsx
import { useMemo } from 'react'
import { cn } from '@/utils/cn'
import { Avatar } from '../Avatar'
import { Badge } from '../Badge'
import { buttonVariants } from '../Button'
import { MemberzoneMenus } from './MemberzoneMenus'
import { SocialMedia } from './SocialMedia'
import { defaultSubscriptions } from './defaults'
import type {
  MemberzoneUser,
  MemberzoneTemplate,
  MemberzoneSubscription,
  MemberzoneMenuItem,
  SocialLink,
} from './types'

const SUBSCRIPTION_DETAIL_URL = 'https://tempo.co/users/subscriptions'

function orderSubscriptions(
  subscriptions: MemberzoneSubscription[],
  templateFor: MemberzoneTemplate,
): MemberzoneSubscription[] {
  const ordered = [...subscriptions]
  if (templateFor === 'teras') {
    const idx = ordered.findIndex((s) => s.name === 'Teras')
    if (idx > -1) {
      const [teras] = ordered.splice(idx, 1)
      ordered.unshift(teras)
    }
  } else if (templateFor === 'tempo') {
    const order = ['Tempo Plus', 'Teras', 'Tempo VIP']
    ordered.sort((a, b) => order.indexOf(a.name) - order.indexOf(b.name))
  }
  return ordered
}

function isSubscriptionActive(subscription: MemberzoneSubscription, user: MemberzoneUser): boolean {
  if (subscription.isVip) return Boolean(user.vipSubscription)
  if (!subscription.accessKey) return false
  return Boolean(user.contentAccess?.includes(subscription.accessKey))
}

export interface MemberzoneSectionProps {
  user: MemberzoneUser
  templateFor: MemberzoneTemplate
  ssoUrl: string
  /** When true, renders compact (no subscription panel) — e.g. inline sidebar usage. */
  isSidebar?: boolean
  subscriptions?: MemberzoneSubscription[]
  menuItems?: MemberzoneMenuItem[]
  socialLinks?: SocialLink[]
  /** Active path for menu highlighting. Defaults to window.location.pathname. */
  currentPath?: string
  /** Called when the user activates "Keluar" (logout). */
  onLogout?: () => void
  className?: string
}

/** User info + subscription status + account menus. The body of the Memberzone drawer. */
export function MemberzoneSection({
  user,
  templateFor,
  ssoUrl,
  isSidebar = false,
  subscriptions = defaultSubscriptions,
  menuItems,
  socialLinks,
  currentPath,
  onLogout,
  className,
}: MemberzoneSectionProps) {
  const ordered = useMemo(
    () => orderSubscriptions(subscriptions, templateFor),
    [subscriptions, templateFor],
  )

  return (
    <div className={cn(isSidebar && 'max-h-[90dvh] w-full overflow-y-auto pb-20 lg:pb-0', className)}>
      <div className="flex gap-3 overflow-hidden px-6 py-4">
        <Avatar size="lg" initials={user.initial} alt={user.fullname} />
        <div>
          <p className="mb-1 line-clamp-1 text-lg font-semibold leading-6 text-neutral-900">
            {user.fullname}
          </p>
          <p className="mb-1 line-clamp-1 text-sm font-semibold leading-4 text-neutral-500 lg:min-w-52">
            {user.email}
          </p>
          <p className="text-sm font-normal leading-4 text-neutral-500">Tempo ID : {user.id}</p>
        </div>
      </div>

      {!isSidebar && (
        <div className="px-5">
          <p className="mb-4 text-lg font-bold">Status Langganan</p>
          <div className="rounded-xl bg-white p-5">
            {ordered.map((subscription) => {
              const active = isSubscriptionActive(subscription, user)
              const Icon = subscription.icon
              return (
                <div
                  key={subscription.name}
                  className="mb-4 flex items-center gap-3 border-b border-neutral-200 pb-4"
                >
                  <Icon className="mt-1 h-[19px] w-[19px]" aria-hidden="true" />
                  <a
                    href={subscription.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm font-semibold text-neutral-900 underline"
                  >
                    {subscription.name}
                  </a>
                  <Badge variant={active ? 'success' : 'danger'} className="ms-auto">
                    {active ? 'Aktif' : 'Tidak Aktif'}
                  </Badge>
                </div>
              )
            })}

            <a
              href={SUBSCRIPTION_DETAIL_URL}
              target="_blank"
              rel="noopener noreferrer"
              className={cn(buttonVariants(), 'mt-4 w-full')}
            >
              Lihat Detail Langganan
            </a>
          </div>
        </div>
      )}

      <MemberzoneMenus
        templateFor={templateFor}
        isSidebar={isSidebar}
        ssoUrl={ssoUrl}
        menuItems={menuItems}
        currentPath={currentPath}
        onLogout={onLogout}
      />

      {templateFor === 'teras' && (
        <div className="mt-4 px-5">
          <SocialMedia links={socialLinks} />
        </div>
      )}
    </div>
  )
}
